Fix for cargo publish
Without the path specified, there was an error
```
cargo publish --dry-run
error: failed to verify package tarball

Caused by:
  can't find `demo` example at `examples/demo.rs` or
  `examples/demo/main.rs`. Please specify example.path if you want to
  use a non-default path.
```